In [1]:
import numpy as np

In [11]:
# Bug 1
prices = np.array([100, 200, 300, 400, 500])
discount = 0.1
final = prices-(prices * discount)
print("After 10% discount:", final)  # Expected: [90, 180, 270, 360, 450]

# Bug 2
matrix = np.zeros((3, 3))  # create 3x3 zero matrix
print(matrix)

# Bug 3
a = np.array([1, 2, 3])
b = np.array([4, 5,5])
print(a + b)  # Expected: [5, 7, 8]

After 10% discount: [ 90. 180. 270. 360. 450.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[5 7 8]
