In [1]:
import numpy as np

In [7]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])

b = np.array([[1],[2]])


print(a + b)


prices = np.array([[100],[200],[300]])
tax = np.array([0.1, 0.2])
final = prices * tax
print(final)
tax = np.array([0.1])           
final = prices * tax
print(final)

tax = np.array([0.1, 0.2, 0.3])
final = prices * tax
print(final)

[[2 3 4]
 [6 7 8]]
[[10. 20.]
 [20. 40.]
 [30. 60.]]
[[10.]
 [20.]
 [30.]]
[[10. 20. 30.]
 [20. 40. 60.]
 [30. 60. 90.]]
