In [1]:
import numpy as np

In [11]:
sales = np.array([[200, 300, 400],
                  [150, 250, 350],
                  [100, 200, 300]])
print(sales+50)
print(np.array([1.1,1.2,1.3]).reshape(3,1))
multiplied_value=sales* (np.array([1.1,1.2,1.3]).reshape(3,1))
print(multiplied_value)
print(multiplied_value.shape)
monthly_mean=np.mean(sales,axis=0)
print(monthly_mean)
print(sales-monthly_mean)

[[250 350 450]
 [200 300 400]
 [150 250 350]]
[[1.1]
 [1.2]
 [1.3]]
[[220. 330. 440.]
 [180. 300. 420.]
 [130. 260. 390.]]
(3, 3)
[150. 250. 350.]
[[ 50.  50.  50.]
 [  0.   0.   0.]
 [-50. -50. -50.]]
