In [1]:
import numpy as n

In [ ]:
student_mark=n.random.randint(0,101,size=10)

In [14]:
print(student_mark)

[43 55 12  3 53 49 15 41 75 15]


In [15]:
print(max(student_mark))
print(min(student_mark))
print((sum(student_mark)/10))

75
3
36.1


In [ ]:
boolarray=student_mark>=50


In [23]:
print(boolarray)

[False  True False False  True False False False  True False]


In [30]:
passed_students_count=n.sum(~boolarray)
print(passed_students_count)

7


In [32]:
import numpy as np

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Bug 1 — get element 6
print(matrix[1][2])

# Bug 2 — get entire second column
print(matrix[:, 1:2])

# Bug 3 — get elements greater than 5
print(matrix[matrix > 5])

6
[[2]
 [5]
 [8]]
[6 7 8 9]


In [35]:
# Given this sales data
sales = np.array([120, 450, 89, 670, 230, 910, 340, 780, 150, 560])

# 1. Get first 3 sales
# 2. Get last 2 sales  
# 3. Get every alternate sale (0,2,4...)
# 4. Get all sales above 400
# 5. Get sales between 200 and 700
# 6. Replace all sales below 100 with 100 (floor value)
print(sales[:3])
print(sales[-2:])
print(sales[::2])
print(sales[sales>400])
print(sales[(sales>200) & (sales<700)])
sales1=sales[sales<100]=100
print(sales1)

[120 450  89]
[150 560]
[120  89 230 340 150]
[450 670 910 780 560]
[450 670 230 340 560]
100
