In [1]:
import numpy as np

In [3]:
arr=np.array([4,9,16,25])
print(np.sqrt(arr))
print(np.log(arr))
print(np.exp(arr))
print(np.abs(np.array([-27,-21])))
print(np.sum(arr))
print(np.cumsum(arr))
np.arange(0,10,2)
np.linspace(0,10,20)

[2. 3. 4. 5.]
[1.38629436 2.19722458 2.77258872 3.21887582]
[5.45981500e+01 8.10308393e+03 8.88611052e+06 7.20048993e+10]
[27 21]
54
[ 4 13 29 54]


array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])