In [1]:
import numpy as np

In [ ]:


arr = np.arange(12)  # [0,1,2,3,4,5,6,7,8,9,10,11]
print(arr.shape)
print(arr.reshape(3,4))
print(arr.reshape(4,3))
print(arr.reshape(2,6))
print(arr.reshape(12,1))
# 1. Reshape to 3 rows, 4 cols
# 2. Reshape to 4 rows, 3 cols
# 3. Reshape to 2 rows, 6 cols
# 4. Reshape to 12 rows, 1 col
# 5. This will fail — why?
print(arr.reshape(6, 2))

(12,)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]]


array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])